// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/pages/article
pub mod article;

// src/components/pages/blog
pub mod blog;

// src/components/pages/careers
pub mod careers;

// src/components/pages/demo
pub mod demo;
pub use demo::Demo;

// src/components/pages/docs
pub mod docs;
