version: "3"
# Run by doing docker compose -f docker-compose.local.yml build --build-arg PG_MAJOR_VER=14
# docker compose -f docker-compose.local.yml up
services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 100
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/14/main/
volumes:
  postgres-data:
