// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/layouts/marketing/base
pub mod base;
pub use base::Base;

// src/components/layouts/marketing/sections
pub mod sections;
