[package]
name = "xgboost-multiclass-classification-example"
version = "0.1.0"
authors = ["Dave Challis <dave@suicas.net>"]
publish = false

[dependencies]
xgboost = { path = "../../" }
log = "0.4"
env_logger = "0.5"
reqwest = { version = "0.11", features = ["blocking"] }
