// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/navigation/tabs/tab
pub mod tab;
pub use tab::Tab;

// src/components/navigation/tabs/tabs
#[allow(clippy::module_inception)]
pub mod tabs;
pub use tabs::Tabs;
