// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/navigation/left_nav/menu/index
pub mod index;
pub use index::Index;

// src/components/navigation/left_nav/menu/item
pub mod item;
pub use item::Item;
