// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/navigation/left_nav/docs
pub mod docs;
pub use docs::Docs;

// src/components/navigation/left_nav/menu
pub mod menu;

// src/components/navigation/left_nav/web_app
pub mod web_app;
pub use web_app::WebApp;
