[tool.poetry]
name = "pgml"
version = "0.6.0"
description = "Python SDK is designed to facilitate the development of scalable vector search applications on PostgreSQL databases."
authors = ["PostgresML <team@postgresml.org>"]
homepage = "https://postgresml.org"
repository = "https://github.com/postgresml/postgresml"
documentation = "https://github.com/postgresml/postgresml/tree/master/pgml-sdks/python/pgml"
readme = "README.md"
packages = [{include = "pgml"}]
keywords = ["postgres","machine learning","vector databases","embeddings"]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
black = "^23.3.0"
rich = "^13.3.5"
psycopg = "^3.1.9"
psycopg-pool = "^3.1.7"
langchain = "^0.0.167"
ipywidgets = "^8.0.6"
datasets = "^2.12.0"
python-dotenv = "^1.0.0"
pypika = "^0.48.9"
pypdf = "^3.9.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
