// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/loading/dots
pub mod dots;
pub use dots::Dots;

// src/components/loading/message
pub mod message;
pub use message::Message;
