// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/layouts/extend_head
pub mod extend_head;
pub use extend_head::ExtendHead;

// src/components/layouts/head
pub mod head;
pub use head::Head;
