// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/layouts/docs
pub mod docs;
pub use docs::Docs;

// src/components/layouts/head
pub mod head;
pub use head::Head;

// src/components/layouts/marketing
pub mod marketing;

// src/components/layouts/product
pub mod product;
