// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/pages/blog/blog_search/call
pub mod call;
pub use call::Call;

// src/components/pages/blog/blog_search/response
pub mod response;
pub use response::Response;
