// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/pages/docs/article
pub mod article;
pub use article::Article;

// src/components/pages/docs/landing_page
pub mod landing_page;
pub use landing_page::LandingPage;
