// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/sections/footers/marketing_footer
pub mod marketing_footer;
pub use marketing_footer::MarketingFooter;
