// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/tables/large/row
pub mod row;
pub use row::Row;

// src/components/tables/large/table
pub mod table;
pub use table::Table;
