# Generated by Django 4.0.6 on 2022-08-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotebookLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "line_type",
                    models.IntegerField(choices=[(1, "Markdown"), (2, "Plain text"), (3, "SQL"), (4, "Empty")]),
                ),
                ("contents", models.TextField(blank=True, null=True)),
                ("nodebook", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="notebooks.notebook")),
            ],
        ),
    ]
