# Generated by Django 4.0.6 on 2022-08-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0002_rename_nodebook_notebookline_notebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookline",
            name="line_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="notebookline",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
