# Generated by Django 4.0.6 on 2022-08-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0003_notebookline_line_number_notebookline_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookline",
            name="rendering",
            field=models.TextField(blank=True, null=True),
        ),
    ]
