# Generated by Django 4.0.6 on 2022-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0004_notebookline_rendering"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookline",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
