# Generated by Django 4.0.6 on 2022-08-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0005_notebookline_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notebookline",
            name="execution_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
