# Generated by Django 4.0.4 on 2022-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebooks", "0006_notebookline_execution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notebook",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
