// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/stimulus/stimulus_action
pub mod stimulus_action;
pub use stimulus_action::StimulusAction;

// src/components/stimulus/stimulus_target
pub mod stimulus_target;
pub use stimulus_target::StimulusTarget;
