// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/pages/blog/blog_search
pub mod blog_search;

// src/components/pages/blog/landing_page
pub mod landing_page;
pub use landing_page::LandingPage;
