// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/navigation/anchor
pub mod anchor;
pub use anchor::Anchor;

// src/components/navigation/tabs
pub mod tabs;
