// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/tables/large
pub mod large;

// src/components/tables/serverless_models
pub mod serverless_models;
pub use serverless_models::ServerlessModels;

// src/components/tables/serverless_pricing
pub mod serverless_pricing;
pub use serverless_pricing::ServerlessPricing;

// src/components/tables/small
pub mod small;
