// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/headings/blue
pub mod blue;
pub use blue::Blue;

// src/components/headings/gray
pub mod gray;
pub use gray::Gray;

// src/components/headings/green
pub mod green;
pub use green::Green;
