// This file is automatically generated.
// You shouldn't modify it manually.

<% if root { %>
pub mod component;
pub use component::{component, Component};
<% } %>
<% for component in modules.iter() { %>
// <%= component.full_path() %>
pub mod <%= component.name() %>;
<% if !component.is_node() { %>
pub use <%= component.name() %>::<%= component.rust_name() %>;
<% } %>
<% } %>
