# Generated by Django 4.0.4 on 2022-08-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="query",
            options={"verbose_name_plural": "queries"},
        ),
    ]
