[package]
name = "rust_bridge_traits"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "The traits for the rust_bridge crate"

[dependencies]
neon = { version = "0.10", default-features = false, features = ["napi-6"] }
