# Generated by Django 4.0.7 on 2022-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_notebook_notebookcell"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_type", models.IntegerField(choices=[(1, "CSV"), (2, "JSON")], default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
