name: push docker images
on:
  workflow_dispatch:
    inputs:
      version:
        default: "2.7.4"
      postgresmlVersion:
        default: "2.7.4-1"
jobs:
  publish-extension-docker-image:
    strategy:
      matrix:
        os: ["buildjet-4vcpu-ubuntu-2204"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: pgml-extension/docker/postgresml
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use --name mybuilder
          docker buildx build  \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/postgresml/postgresml:${{ inputs.version }} \
            --build-arg POSTGRESML_VERSION=${{ inputs.postgresmlVersion }} \
            --push .
