// This file is automatically generated.
// You shouldn't modify it manually.

// src/components/sections/common_resources
pub mod common_resources;
pub use common_resources::CommonResources;

// src/components/sections/footers
pub mod footers;

// src/components/sections/have_questions
pub mod have_questions;
pub use have_questions::HaveQuestions;
