[package]
name = "xgboost-basic-example"
version = "0.1.0"
authors = ["Dave Challis <dave@suicas.net>"]
publish = false

[dependencies]
xgboost = { path = "../../" }
sprs = "0.11"
log = "0.4"
env_logger = "0.5"
